<?php
/* Author: Philip Weir */

$labels = [];
$labels['mailtip'] = 'Select a message to read';
$labels['contacttip'] = 'Select a contact to view';
$labels['settingstip'] = 'Select a category to view or edit settings';
$labels['folderstip'] = 'Select a folder to view or edit';
$labels['identitiestip'] = 'Select an identity to view or edit';
$labels['responsestip'] = 'Select a response to view or edit';
$labels['filterstip'] = 'Select a rule to view or edit';
$labels['enigmatip'] = 'Select a key to view or edit';
$labels['displayfirst'] = 'Always open the first message in the list';

$messages = [];
$messages['clickdisplayfirst'] = 'Click here to always open the first message in the list';
