<?php
/* Author: Marcelo Leães */

$labels = array();
$labels['mailtip'] = 'Selecione uma mensagem na lista para abri-la';
$labels['contacttip'] = 'Selecione um contato da lista para visualizar';
$labels['settingstip'] = 'Selecione uma categoria para visualizar ou editar';
$labels['folderstip'] = 'Selecione uma pasta para visualizar ou editar';
$labels['identitiestip'] = 'Selecione uma identidade para visualizar ou editar';
$labels['responsestip'] = 'Selecione uma resposta para visualizar ou editar';
$labels['filterstip'] = 'Selecione uma regra para visualizar ou editar';
$labels['enigmatip'] = 'Selecione uma chave para visualizar ou editar';
$labels['displayfirst'] = 'Sempre abrir a primeira mensagem da lista';

$messages = array();
$messages['clickdisplayfirst'] = 'Clique aqui para sempre abrir a primeira mensagem da lista';
